defaults:
  - default.yaml

#strategy:
#  _target_: pytorch_lightning.strategies.DeepSpeedStrategy
#  accelerator: 'gpu'
#  stage: 2

#strategy: 'deepspeed_stage_2_offload'
strategy: 'deepspeed_stage_2'
precision: 16
sync_batchnorm: True
#accumulate_grad_batches: 4
#gradient_clip_val: 0.5