_target_: pytorch_lightning.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1
max_epochs: 2

accelerator: gpu
strategy: 'ddp_spawn'
devices: [2,3]
num_nodes: 1
check_val_every_n_epoch: 2 #5
num_sanity_val_steps: 1
deterministic: False
# precision: 16
# accumulate_grad_batches: 4
