defaults:
  - default.yaml

strategy:
  _target_: pytorch_lightning.strategies.DDPFullyShardedNativeStrategy
  cpu_off_load:
    _target_: torch.distributed.fsdp.fully_sharded_data_parallel.CPUOffload
    offload_params: True

#strategy: 'deepspeed_stage_2_offload'
#strategy: 'deepspeed_stage_2'
precision: 16
sync_batchnorm: True
#accumulate_grad_batches: 4
#gradient_clip_val: 0.5