
root_dir: ${oc.env:PROJECT_ROOT} # path to root directory
data_dir: ${paths.root_dir}/data # path to data directory
log_dir: ${paths.root_dir}/logs/ # path to logging directory
output_dir: ${hydra:runtime.output_dir} # path to output directory, created dynamically by hydra
work_dir: ${hydra:runtime.cwd} # path to working directory
