# https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.callbacks.ModelCheckpoint.html

model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${paths.log_dir}
  filename: 'epoch_{epoch:03d}' 
  monitor: 'total_loss' 
  #monitor: 'uAP' 
  verbose: False 
  save_last: null 
  save_top_k: 1
  mode: "min" 
  #mode: "max" 
  auto_insert_metric_name: False
  save_weights_only: False 
  every_n_train_steps: null
  train_time_interval: null
  every_n_epochs: 2
  save_on_train_epoch_end: null 
