# https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.callbacks.ModelCheckpoint.html

model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}
  filename: '{epoch}-{loss:.2f}' 
  monitor: 'uAP' 
  verbose: False 
  save_last: null 
  save_top_k: 3
  mode: "min" 
  auto_insert_metric_name: False
  save_weights_only: False 
  every_n_train_steps: null
  train_time_interval: null
  every_n_epochs: 2
  save_on_train_epoch_end: null 
