# @package _global_


defaults:
  - _self_
  - datamodule: copydetect.yaml
  - model: copydetect.yaml
  - callbacks: default.yaml
  - logger: null
#  - logger: wandb.yaml
  - trainer: default.yaml
#  - trainer: deepspeed.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - experiment: null
  - hparams_search: null
  - optional local: default.yaml
  - debug: null


task_name: "copydetection"
tags: ["dev"]

train: True
test: False
ckpt_path: null

seed: null
