_target_: src.datamodules.disc_datamodule.CopyDetectorDataModule

train_path: ${paths.data_dir}/disc21/images/train/
ref_path: ${paths.data_dir}/disc21/images/references/
val_query_path: ${paths.data_dir}/disc21/images/queries/
test_query_path: ${paths.data_dir}/disc21/images/queries/
#test_query_path: ${paths.data_dir}/disc21/final_queries/
val_gt_path: ${paths.data_dir}/disc21/groundtruth/subset_1_ground_truth.csv
#val_gt_path: ${paths.data_dir}/disc21/groundtruth/dev_ground_truth.csv
#test_gt_path: ${paths.data_dir}/disc21/groundtruth/final_ground_truth.csv
test_gt_path: ${paths.data_dir}/disc21/groundtruth/subset_1_ground_truth.csv
ref_subset_path: ${paths.data_dir}/disc21/groundtruth/subset_1_references.txt
query_subset_path: ${paths.data_dir}/disc21/groundtruth/subset_1_queries.txt
train_batch_size: 32
train_img_size: 224 
val_batch_size: 32
val_img_size: 224
test_batch_size: 2
test_img_size: 384
workers: 16
n_weak_aug: 1
n_strong_aug:  3
n_repeat_aug:  1

