_target_: src.datamodules.disc_datamodule.CopyDetectorDataModule

train_path: ${data_dir}/train/
ref_path: ${data_dir}/references/
val_query_path: ${data_dir}/dev_queries/
test_query_path: ${data_dir}/dev_queries/
#test_query_path: ${data_dir}/final_queries/
val_gt_path: ${data_dir}/groundtruth/subset_1_ground_truth.csv
#val_gt_path: ${data_dir}/groundtruth/dev_ground_truth.csv
#test_gt_path: ${data_dir}/groundtruth/final_ground_truth.csv
test_gt_path: ${data_dir}/groundtruth/subset_1_ground_truth.csv
ref_subset_path: ${data_dir}/groundtruth/subset_1_references.txt
query_subset_path: ${data_dir}/groundtruth/subset_1_queries.txt
train_batch_size: 2
train_img_size: 224 
val_batch_size: 2
val_img_size: 224
test_batch_size: 2
test_img_size: 384
workers: 10
n_weak_aug: 1
n_strong_aug:  3
n_repeat_aug:  1

