_target_: src.datamodules.disc_datamodule.CopyDetectorDataModule

train_path: ${paths.data_dir}/disc21/train/
#train_path: ${paths.data_dir}/disc21/references/
ref_path: ${paths.data_dir}/disc21/references/
val_query_path: ${paths.data_dir}/disc21/queries/
test_query_path: ${paths.data_dir}/disc21/queries/
#test_query_path: ${paths.data_dir}/disc21/final_queries/
val_gt_path: ${paths.data_dir}/groundtruth/subset_1_ground_truth.csv
#val_gt_path: ${paths.data_dir}/groundtruth/dev_ground_truth.csv
#test_gt_path: ${paths.data_dir}/groundtruth/final_ground_truth.csv
test_gt_path: ${paths.data_dir}/groundtruth/subset_1_ground_truth.csv
#ndec_path: ${paths.data_dir}/ndec/train
#test_query_path: ${paths.data_dir}/ndec/query_images_h5
#test_gt_path: ${paths.data_dir}/groundtruth/public_ground_truth_h44.csv
ref_subset_path: ${paths.data_dir}/groundtruth/subset_1_references.txt
query_subset_path: ${paths.data_dir}/groundtruth/subset_1_queries.txt
train_batch_size: 4
train_img_size: 224 
val_batch_size: 4
val_img_size: 224
test_batch_size: 2
test_img_size: 384
workers: 16
n_weak_aug: 1
n_strong_aug:  3
n_repeat_aug:  1

